name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Alternative FTP deployment method
    - name: Deploy to Hostinger via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.HOSTINGER_FTP_HOST }}
        user: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD  }}
        remoteDir: '/public_html/'
